name: Deliverable
description: Create a deliverable or project outcome task
title: "[Deliverable] "
labels: [deliverable]
body:
  - type: input
    id: title
    attributes:
      label: Deliverable Title
      placeholder: "e.g., Spark SQL Query Optimization Project"
    validations:
      required: true

  - type: dropdown
    id: week
    attributes:
      label: Target Completion Week
      options:
        - "W1"
        - "W2"
        - "W3"
        - "W4"
        - "W5"
        - "W6"
        - "W7"
        - "W8"
        - "W9"
        - "W10"
        - "W11"
        - "W12"
    validations:
      required: true

  - type: dropdown
    id: track
    attributes:
      label: Track
      options:
        - "Common"
        - "DE"
        - "ML"
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: Time Estimate (hours)
      placeholder: "8"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "P0"
        - "P1"
        - "P2"
      default: 0

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the deliverable? What are the requirements?
      placeholder: "Describe the project, requirements, and acceptance criteria"
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Resources & Links
      description: Relevant documentation, templates, or resources
      placeholder: "- Link to docs\n- Reference materials"

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will this deliverable be evaluated?
      placeholder: "- Criterion 1\n- Criterion 2"
    validations:
      required: true
